<?php
$catalogue = [
  'shri-radha-sharnam' => ['name'=>'Shri Radha Sharnam','type'=>'Residential · Keshav Dham Road','price'=>'From ₹74.65 L','status'=>'Ready to move','image'=>'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=2200&q=90','description'=>'Fully furnished residences designed for long weekends, longer stays and a life at a gentler pace.'],
  'raal-road-township' => ['name'=>'RAAL Road Township','type'=>'Plots & land · NH-19, Chatikara','price'=>'From ₹120 / sq. yd.','status'=>'Selling now','image'=>'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=2200&q=90','description'=>'A considered township with generous green spaces, clear titles and room to make your own.'],
  'shri-vivek-heritage' => ['name'=>'Shri Vivek Heritage','type'=>'Commercial · High street, Vrindavan','price'=>'From ₹55 L','status'=>'Upcoming','image'=>'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=2200&q=90','description'=>'Distinctive commercial spaces positioned for visibility, footfall and the next chapter of Vrindavan.'],
  'vrindawali-farms' => ['name'=>'Vrindawali Farms & Residency','type'=>'Plots & land · Vrindavan','price'=>'From ₹28,000 / sq. yd.','status'=>'Selling now','image'=>'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=2200&q=90','description'=>'Farmhouse living with open skies, landscaped avenues and a softer rhythm of everyday life.'],
];
$key = $_GET['project'] ?? 'shri-radha-sharnam';
$project = $catalogue[$key] ?? $catalogue['shri-radha-sharnam'];
?>
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="description" content="<?= htmlspecialchars($project['name']) ?> — <?= htmlspecialchars($project['description']) ?>"><title><?= htmlspecialchars($project['name']) ?> | Braj Kutir</title>
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Playfair+Display:ital,wght@0,500;0,600;1,500;1,600&display=swap" rel="stylesheet"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"><link rel="stylesheet" href="styles.css"></head>
<body class="detail-page">
<nav class="navbar premium-nav" id="navbar"><div class="container"><a href="index.php" class="nav-logo"><span class="home-mark">BK</span><span class="home-logo-word">Braj Kutir<small>REAL ESTATE</small></span></a><div class="nav-links"><a href="index.php">Home</a><a href="projects.php">Projects</a><a href="aboutus.php">About us</a><a href="invest-in-vrindavan.php">Why Vrindavan</a><a href="#enquire" class="nav-cta">Schedule a visit</a></div><button class="nav-hamburger" aria-label="Open menu"><span></span><span></span><span></span></button></div></nav>
<div class="mobile-menu" id="mobileMenu"><button class="mobile-menu-close">&times;</button><a href="index.php">Home</a><a href="projects.php">Projects</a><a href="aboutus.php">About us</a><a href="invest-in-vrindavan.php">Why Vrindavan</a><a href="#enquire">Schedule a visit</a></div>
<main>
<section class="detail-hero" style="--detail-image:url('<?= htmlspecialchars($project['image']) ?>')"><div class="detail-hero-shade"></div><div class="container detail-hero-content"><a class="back-link" href="projects.php"><i class="fas fa-arrow-left"></i> All projects</a><span class="home-eyebrow"><?= htmlspecialchars($project['type']) ?></span><h1><?= htmlspecialchars($project['name']) ?></h1><p><?= htmlspecialchars($project['description']) ?></p><a href="#enquire" class="home-button home-button-light">Request a private viewing <i class="fas fa-arrow-right"></i></a></div><div class="detail-status"><?= htmlspecialchars($project['status']) ?></div></section>
<section class="detail-overview section"><div class="container detail-overview-grid"><div><span class="home-eyebrow">A considered address</span><h2>Space to live<br><em>more fully.</em></h2><p><?= htmlspecialchars($project['description']) ?> Every detail is shaped around the rituals that make Vrindavan feel like home — unhurried mornings, meaningful gatherings and the freedom to stay a little longer.</p></div><div class="overview-facts"><div><small>Starting from</small><strong><?= htmlspecialchars($project['price']) ?></strong></div><div><small>Address</small><strong>Vrindavan, Uttar Pradesh</strong></div><div><small>Possession</small><strong><?= htmlspecialchars($project['status']) ?></strong></div><div><small>Curated by</small><strong>Braj Kutir</strong></div></div></div></section>
<section class="cinematic-gallery"><div class="container"><div class="gallery-heading"><span class="home-eyebrow">See it in a new light</span><h2>Made for the<br><em>way you want to live.</em></h2></div><div class="gallery-grid"><div class="gallery-tall" style="background-image:url('<?= htmlspecialchars($project['image']) ?>')"></div><div class="gallery-wide gallery-detail-2"></div><div class="gallery-wide gallery-detail-3"></div></div></div></section>
<section class="detail-features section"><div class="container detail-feature-grid"><div><span class="home-eyebrow">The details</span><h2>Everything<br><em>in its place.</em></h2><p>A thoughtful foundation for days that feel spacious, connected and entirely your own.</p></div><div class="feature-list"><div><i class="fas fa-house"></i><span><strong>Thoughtful layouts</strong><small>Plans that make every square foot feel intentional.</small></span></div><div><i class="fas fa-leaf"></i><span><strong>Green open spaces</strong><small>Landscape and light woven into the everyday.</small></span></div><div><i class="fas fa-shield-halved"></i><span><strong>Peace of mind</strong><small>Clear documentation and a trusted partner beside you.</small></span></div><div><i class="fas fa-road"></i><span><strong>Connected location</strong><small>Close to the places that matter in Vrindavan.</small></span></div></div></div></section>
<section class="floor-plan-section"><div class="container"><span class="home-eyebrow">Plans & possibilities</span><h2>A plan for<br><em>your kind of life.</em></h2><div class="floor-plans"><div><div class="plan-drawing"><span>01</span><i class="fas fa-expand"></i></div><strong>Typical floor plan</strong><small>Well-proportioned spaces</small></div><div><div class="plan-drawing plan-two"><span>02</span><i class="fas fa-expand"></i></div><strong>Site plan</strong><small>Landscape and connectivity</small></div></div></div></section>
<section class="location-section section"><div class="container location-grid"><div class="location-map"><div class="map-pin"><i class="fas fa-location-dot"></i><span><?= htmlspecialchars($project['name']) ?></span></div></div><div><span class="home-eyebrow">A place within a place</span><h2>Close to the<br><em>heart of Braj.</em></h2><p>From temple bells to the Yamuna, your everyday is connected to the experiences that make Vrindavan unique.</p><ul class="connectivity"><li><span>Prem Mandir</span><strong>08 min</strong></li><li><span>Banke Bihari Temple</span><strong>15 min</strong></li><li><span>Yamuna Expressway</span><strong>25 min</strong></li></ul></div></div></section>
<section class="trust-section"><div class="container"><span class="home-eyebrow">A partner you can count on</span><h2>Property guidance,<br><em>with perspective.</em></h2><div class="trust-points"><span><strong>15+</strong> Mn sq. ft. under development</span><span><strong>5,000+</strong> Families guided home</span><span><strong>01</strong> Dedicated Vrindavan team</span></div></div></section>
<section class="project-enquiry" id="enquire"><div class="container"><div><span class="home-eyebrow">Make it yours</span><h2>Come see it<br><em>for yourself.</em></h2><p>Leave your details and our advisor will arrange a private conversation around <?= htmlspecialchars($project['name']) ?>.</p></div><form id="contactForm" class="enquiry-form"><input name="name" placeholder="Your name" required><input name="phone" placeholder="Phone number" required><input name="email" type="email" placeholder="Email address"><button class="home-button home-button-light" type="submit">Request a private viewing <i class="fas fa-arrow-right"></i></button></form></div></section>
</main><script src="script.js"></script></body></html>
